POST http://localhost:3005/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im13YW1id2EiLCJpZCI6IjY3YzVjNjljODUyMDA3MGMzOTVjY2VlNSIsImlhdCI6MTc0MTAxNDcxNn0.XPS9y0c85sSYD7QWQZqJp1FLjbOyYS58pOUz2GY1ktA

{
    "title": "how i love my dearest dad",
    "author": "christopher mamba munyumbwe",
    "url": "www.mwambwamaamba.com",
    "likes": 122
}